# mkdocs.yml
site_name: Trappy-Scopes (scope-cli)
site_url: https://trappy-scopes.github.io/scope-cli
repo_url: https://github.com/Trappy-Scopes/scope-cli

nav:
  - Home: index.md
  - Introduction: notes/intro.md
  - hive:
      - Overview: hive/index.md
      - API Reference: hive/hive.md
  - expframework:
      - Overview: expframework/index.md
      - API Reference: expframework/api.md
  - core:
      - Overview: core/index.md
      - API Reference: core/api.md
  - optics:
      - Overview: optics/index.md
      - API Reference: optics/api.md
  - Notes:
      - Introduction: notes/assmble_trappy_scopes.md
      - Hive: notes/hive.md       
      - Optics: notes/optics.md
      - Project Management: notes/projectman.md
      - Devices: notes/devices.md            
      - picamera2 API: notes/picamera2.md
  - All Trappy-Scopes Projects: https://trappy-scopes.github.io







plugins:
  - search
  - blogging
  - external-markdown
  - mermaid2

#  - autorefs
#  - redirects
#      scripts:
#        - generate_docs.py

extra:
  homepage: https://trappy-scopes.github.io/trappyscopes/

theme:
  logo: assets/tsicon.png
  name: material
  palette:
    # Dark mode as default
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode option
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences