# mkdocs.yml
site_name: Trappy-Scopes cli (scope-cli)
docs_dir: _docs_     # Source files here
site_dir: .    # Output goes here
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
repo_url: https://github.com/Trappy-Scopes/scope_cli

nav:
  - Home: index.md