# mkdocs.yml
site_name: Trappy-Scopes (scope-cli)
site_url: https://trappy-scopes.github.io/scope-cli
repo_url: https://github.com/Trappy-Scopes/scope-cli

nav:
  - Home: index.md
  - core:
      - Overview: core/index.md
      - API Reference: core/api.md
  - expframework:
      - Overview: expframework/index.md
      - API Reference: expframework/api.md
  

plugins:
  - search
#  - autorefs
#  - redirects
#      scripts:
#        - generate_docs.py


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html