#!/bin/bash


## Only works on linux machines
hanme=hostname

#sudo chrt -r 98 tmux -T 256 new-session -s $hname

#tmux send-keys -t $hanme "python -i main.py" #"${@:2:99}"'

#python -i main.py "${@:2:99}"

## ------------------------------------------
## TRAPPY-SCOPES launch script
## 
##
## ------------------------------------------

echo "------------------------------------------------"
value="$(python startup.py)"
echo "${value}"


# Set IFS to newline to process each line correctly
IFS=$'\n'

# Loop over each line and process only those that contain '='
for line in $value; do
    if [[ "$line" == *"="* ]]; then
        eval "$line"
    fi
done
#echo $ui_mode

## ------------- Run what needs to be run -----------
eval "$to_run"
## ------------- Run what needs to be run -----------

echo "------------------------------------------------"
if [ "$ui_mode" == "interactive" ]; then
	python -i main.py "${@:1:99}"
elif [ "$ui_mode" == "gui" ]; then
	python viewer.py --noep "${@:1:99}"
else
	echo "Invalid trappy-ui mode!"
fi


#{ python startup.py; result=$?; } || true
# the result of a.py is in $result
#