name: MDev
uuid: null
type: microscope
hardware:
  pico:
  - nullpico
  - pico1
  - nullpico
  camera: nullcamera
  illumination: CA_PWM_RGB_LED_5mm
git_sync: true
write_server: ssd1
file_server: /Volumes/ssd1/scopeportintest
auto_fsync: true
auto_pico_fsync: true
