# Do Not change ----------------
name      : M1
uuid      : null
type      : microscope
# ------------------------------

hardware:
  pico         : [nullpico, pico1, null]
  camera       : nullcamera
  illumination : CA_PWM_RGB_LED_5mm

