name: null
uuid: null
type: null
frame: null
optics:
  lenses: null
hardware:
  pico: null
  camera: null
  illumination: null
git_sync: null
write_server: null
file_server: null
auto_fsync: null
auto_pico_fsync: null
